# Generated by Django 4.2.11 on 2024-03-15 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "referrals",
            "0002_remove_referralcode_referral_code_referralcode_code_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralcode",
            name="is_active",
        ),
    ]
